server:
  port: 8081
  #jsp-servlet:
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    name: uc
    type: com.alibaba.druid.pool.DruidDataSource
# ready:
      ##      #type: com.alibaba.druid.pool.DruidDataSource
      ##      driver-class-name: com.mysql.jdbc.Driver
      ##      initialize: true
      ##      name: zentaopro
      ##      url: jdbc:mysql://127.0.0.1:3308/uc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    ##      username: root
    ##      password: root
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/uc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: fj
      password: chm
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#spring:
#  datasource:
#    slave:
#      url: jdbc:mysql://localhost:3308/uc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: root
#      password: root
#      filters: mergeStat
#      on-off: true
#      driver-class-name: com.mysql.jdbc.Driver
#    master:
#      url: jdbc:mysql://localhost:3309/uc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: root
#      password: root
#      filters: mergeStat
#      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/** #配置访问静态文件地址
  resources:
    static-locations: classpath:/static/ #配置访问静态文件地址
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus: #mybatis
  mapper-locations: classpath*:/mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: ac.cn.chm.uc.**.model  # 注意：对应实体类的路径
#mybatis-plus:
  global-config:
    refresh: true #修改xml时，可自动刷新，不需要重新启动
    db-config:
      logic-delete-value: D # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
##pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#api
access:
  key: accessKey
  pass: accessPass
#系统
sys:
  sso: http://localhost:8080/
  uc: http://localhost:8081/
filter:
  user: 123
  maps:
    login: #需要与LoginFilter前缀相同，否则无法获取到信息
      url: /user/* #需要过滤的地址
      order: 1  #过滤器的优化级，值越小优先级越高
    auth:
      url: /test/*
      order: 2